// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://puoqqqysbfhdhbyqljcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1b3FxcXlzYmZoZGhieXFsamNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjAzMTQsImV4cCI6MjA3MTQzNjMxNH0.xrBAVOVuxjx9N5vfSNJoIo-ZZ4EgTddqYz5EIQu6Qps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
